### ISSUE TITLE
react-native run-android --configuration Release Error

### ISSUE THREAD

**Issue by vongohren** [zetachang/react-native-dotenv#6]
Using this command

```react-native run-android --configuration Release```

Gives this error

```error: unknown option '--configuration'```

Any idea?

**Comment by zetachang** [comment]
Which version of react-native are you using?

Snorre Lothar von Gohren Edwin <notifications@github.com> 於 2017年1月19日週四
上午12:14 寫道：

**Comment by Snorlock** [comment]
Im using both ios and android, im currently on 0.38, since there was some bug on 0.40 with cocoa pods.

**Comment by zetachang** [comment]
Looks like Android doesn't have this option... but you could set it through
the dev settings menu. Cmd + M or shake the device to launch the dev menu.

Snorre Lothar von Gohren Edwin <notifications@github.com> 於 2017年1月19日週四
上午12:58 寫道：

**Comment by AVEmedia** [comment]
@zetachang I was getting the same error, too. Yes I'm running 0.32, but I do not have the option of upgrading to 0.40 because of other 3rd party dependencies.

I'm not sure what you mean by 'setting it through the dev settings menu', because when I do Cmd+M, all that does is minimize my simulator window.

So then I tried this:
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "ios-dev": "node node_modules/react-native/local-cli/cli.js run-ios --configuration Debug",
    "ios-prod": "node node_modules/react-native/local-cli/cli.js run-ios --configuration Release"
  },
but unfortunately neither of those scripts could successfully switch out my env variables.

Any way, my workaround was to just manually edit my schema in Xcode.

According to your README instructions, the file that is requesting the dynamic variables should look like this:

import { API_KEY, DATABASE_URL } from 'react-native-dotenv';
ApiClient.init(API_KEY, DATABASE_URL);

const config = {
    apiKey: API_KEY,
    databaseURL: DATABASE_URL
  };

I kept getting ApiClient is not defined, which makes sense because you can't just call a  .init method on ApiClient when ApiClient hasn't even been imported. So I spent a bunch of time trying to figure out where that line of code should go, only to realize a while later, that it's not needed or necessary to make your library work. I really wish that was clearly explained in the README, because you have it in a code block that makes people feel like it has to be inserted somewhere.

Any way, after a lot of fiddling, I finally got it working, and when i deployed the app, everything worked awesome, so thank you @zetachang ... after testing out react-native-config and being unable to make it work, I can say that I like your solution a lot better :-)

**Comment by zetachang** [comment]
@AVEmedia thanks for your detailed report!

> I'm not sure what you mean by 'setting it through the dev settings menu', because when I do Cmd+M, all that does is minimize my simulator window.

Cmd+M works only in Android Emulator, and React Native for iOS doesn't support switch prod/dev in DevSettings menu.

> but unfortunately neither of those scripts could successfully switch out my env variables.

Yeah, The configuration options for `run-ios` is only supported in v0.39.0+.  😢 

> Any way, my workaround was to just manually edit my schema in Xcode.

Any details on this? 

>  I really wish that was clearly explained in the README, because you have it in a code block that makes people feel like it has to be inserted somewhere.

Agreed. Any suggestion on how we could improve on this? I would also love to merge PR for improving documentation. 😃

**Comment by vongohren** [comment]
Closing because there are some fixes on this now
